@startuml refresh

actor User
participant Popup
participant "Other Tab"
participant Tab
participant Client
participant Server
participant "Other Client"

User -> Popup: refresh
Popup -> Client: joinRoom
activate Client
Client -> Server: joinRoom
activate Server
Server -> "Other Client": getUsers
Client <-- Server: callback
deactivate Server
Tab <- Client: update
"Other Tab" <- Client: update
Tab <- Client: changeStateClient
"Other Tab" <- Client: changeStateClient

Tab <- Client: sendInfo
Popup <- Client: sendInfo
"Other Tab" <- Client: sendInfo
Popup <- Client: sendInfo
Tab <- Client: sendInfo
Popup <- Client: sendInfo
deactivate Client

@enduml
