version: "2"

services:
  redis:
    image: redis
    restart: always
    ports:
      - 127.0.0.1:6379:6379
    command: redis-server
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
