@startuml changeVideoServer

participant Client
participant Server
participant "Other Client"

activate Client
Client -> Server: changeVideoServer
activate Server
Server -> "Other Client": changeVideoClient
Client <-- Server : callback
deactivate Server

@enduml
