@startuml joinRoom

participant Client
participant Server
participant "Other Client"

activate Client
Client -> Server: joinRoom
activate Server
Server -> "Other Client": getUsers
Client <-- Server: callback
deactivate Server

@enduml
