@startuml leaveRoom

participant Client
participant Server
participant "Other Client"

activate Client
Client -> Server: leaveRoom
activate Server
Server -> "Other Client": getUsers
Client <-- Server: callback
deactivate Server

@enduml
