@startuml joinRoom

Client -> Server: joinRoom
activate Server
Client <-- Server: callback
Server -> "Other Client": getUsers
Client <-- Server: getUsers
Client <-- Server: changeVideoClient
Client <-- Server: changeStateClient
deactivate Server

@enduml
